apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{  .Values.app  }}
  name: {{  .Release.Name  }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{  .Values.app  }}
      user: {{ .Values.user }}
  template:
    metadata:
      labels:
        app: {{  .Values.app  }}
        user: {{ .Values.user }}
    spec:
      containers:
      - image: 108356037/jupyter-playground:v1
        name: {{  .Values.app  }}-pod
        ports:
          - containerPort: 8888
        volumeMounts:
        - name: {{ .Values.user }}-storage
          mountPath: /home/jovyan/work
        resources:
          requests:
            memory: {{  .Values.ram.min | quote }}
            cpu: {{  .Values.cpu.min | quote }}
            {{ if .Values.enforcegpu }}
            nvidia.com/gpu: 1
            {{ end }}
          # limits:
          #   memory: {{  .Values.ram.max | quote }}
          #   cpu: {{  .Values.cpu.max | quote }}
            {{ if .Values.enforcegpu }}
            nvidia.com/gpu: 1
            {{ end }}
        command: ["jupyter-lab"]
        args:
          - "--no-browser"
          - "--ip"
          - '*'
          - "--NotebookApp.token"
          - ''
          - "--NotebookApp.password"
          - ''
          - "--NotebookApp.base_url"
          - '/playground'
          - '--NotebookApp.disable_check_xsrf'
          - 'True'
          - '--NotebookApp.allow_remote_access'
          - 'True'
          - '--NotebookApp.notebook_dir'
          - '/home/jovyan/work'
          - '--GatewayClient.ws_url'
          - 'wss://{{ .Values.user }}.jupyter.srv.algotrade.dev/'
          - '--NotebookApp.allow_origin'
          - '*'
          - '--NotebookApp.tornado_settings'
          - '{"headers" :{"Content-Security-Policy" :"frame-ancestors self srv.algotrade.dev"}}'
      volumes:
      - name: {{ .Values.user }}-storage
        # pointer to the configuration
        persistentVolumeClaim:
          claimName: {{ .Values.user }}-pvc


        