apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{  .Values.app  }}
    user: {{ .Values.user }}
  name: d-{{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
    name: http
  selector:
    app: {{  .Values.app  }}
    user: {{ .Values.user }}
  type: ClusterIP