apiVersion: v1
name: lab-and-grafana
version: 1.1.0
appVersion: 1.1.0
type: application

dependencies:
- name: grafana
  version: 6.9.3
  repository: "https://grafana.github.io/helm-charts"
  condition: grafana.enabled

- name: jupyter
  version: 0.1.0
  repository: "file://subcharts/jupyter"
  condition: jupyter.enabled