/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:0673a1aa-f95a-4652-9b37-9aa0c635bfc2",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_z2fADDubD",
    "aws_user_pools_web_client_id": "6mr5lbve47dbs0trvbuatqb3tm",
    "oauth": {}
};


export default awsmobile;
