---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grpc-faas-claim
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
  # - ReadWriteMany #the volume can be mounted as read-write by many nodes
  - ReadWriteOnce #he volume can be mounted as read-write by a single node.
  # # ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.
