{{- if .Values.auth.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ .Values.user }}-c9-request-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      user: {{ .Values.user }}-c9
  jwtRules:
  - issuer: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_z2fADDubD
    jwksUri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_z2fADDubD/.well-known/jwks.json
    #forwardOriginalToken: true
    fromHeaders:
    - name: Cookie
      prefix: "id_token="
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.user }}-c9-auth-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      user: {{ .Values.user }}-c9
  action: ALLOW
  rules:
  - when:
    - key: request.auth.claims[iss]
      values: ["https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_z2fADDubD"]

    - key: request.auth.claims[sub]
      values: [{{ .Values.user | quote }}]

    - key: request.auth.claims[cognito:username]
      values: [{{ .Values.user | quote }}]
    
    - key: request.auth.claims[token_use]
      values: ["id"]

    # to:
    # - operation:
    #     methods: ["OPTIONS","GET","POST","PUT","PATCH","UPDATE"]

    # from:
    # - source:
    #     requestPrincipals: ["https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_z2fADDubD/{{ .Values.user }}"]
{{- end }}