{{- if .Values.auth.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ .Values.user }}-grafana-request-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      user: {{ .Values.user }}-grafana
  jwtRules:
  - issuer: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_z2fADDubD
    jwksUri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_z2fADDubD/.well-known/jwks.json
    #forwardOriginalToken: true
    fromHeaders:
    - name: Cookie
      prefix: "id_token="
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.user }}-grafana-auth-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      user: {{ .Values.user }}-grafana
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_z2fADDubD/{{ .Values.user }}"]

    when:
    - key: request.auth.claims[cognito:username]
      values: [{{ .Values.user | quote }}]
    
    - key: request.auth.claims[token_use]
      values: ["id"]
{{- end }}