name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_REG: asia-east1-docker.pkg.dev
  IMAGE_REPO: service-reg
  
jobs:

  grpcfaas:

    env:
      SERVICE_NAME: grpc-faas

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set env
      run: echo "IMAGE_NAME=${{ env.IMAGE_REG }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_REPO }}/${{ env.SERVICE_NAME }}" >> $GITHUB_ENV

    - id: Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud sdk
      uses: google-github-actions/setup-gcloud@v0

    - name: Use gcloud CLI
      run: gcloud info

    - name: Build Docker image
      run: docker build -t ${IMAGE_NAME} -f ./microservice/grpc-faas-v2/Dockerfile ./microservice/grpc-faas-v2/

    - name: Configure docker to use gcloud
      run: gcloud auth configure-docker asia-east1-docker.pkg.dev

    - name: Push to GCR
      run: docker push ${IMAGE_NAME}


  stg-manager:

    env:
      SERVICE_NAME: strategy-manager

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set env
      run: echo "IMAGE_NAME=${{ env.IMAGE_REG }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_REPO }}/${{ env.SERVICE_NAME }}" >> $GITHUB_ENV

    - id: Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud sdk
      uses: google-github-actions/setup-gcloud@v0

    - name: Use gcloud CLI
      run: gcloud info

    - name: Build Docker image
      run: docker build -t ${IMAGE_NAME} -f ./microservice/strategy-manager/Dockerfile ./microservice/strategy-manager/

    - name: Configure docker to use gcloud
      run: gcloud auth configure-docker asia-east1-docker.pkg.dev

    - name: Push to GCR
      run: docker push ${IMAGE_NAME}