name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "asia-east1-docker.pkg.dev/devops-playground-336005/service-reg" >> $IMAGE_REPO
    - name: Build grpcfaas Docker image
      run: docker build -t ${IMAGE_REPO}/algotrade-grpc-faas-v2 -f ./microservice/grpc-faas-v2/Dockerfile ./microservice/grpc-faas-v2/

