name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  grpcfaas:

    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_REG: asia-east1-docker.pkg.dev/devops-playground-336005
      IMAGE_REPO: service-reg

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Set env
    #   run: echo "IMAGE_REPO=asia-east1-docker.pkg.dev/devops-playground-336005/service-reg" >> $GITHUB_ENV

    - id: Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud sdk
      uses: google-github-actions/setup-gcloud@v0
      # with:
      #   service_account_key: ${{ secrets.GCP_SA_KEY }}
      #   project_id: ${{ secrets.GCP_PROJECT_ID }}
      #   export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_REG }}/${{ env.IMAGE_REPO }}/grpc-faas-service -f ./microservice/grpc-faas-v2/Dockerfile ./microservice/grpc-faas-v2/

    - name: Configure docker to use gcloud
      run: gcloud auth configure-docker -q

    - name: Push to GCR
      run: docker push ${{ env.IMAGE_REG }}/${{ env.IMAGE_REPO }}/grpc-faas-service